const AdminheaderMenuData = [
  {
    label: "Movies",
    label_ko: "영화 산업",
    key_name: "Movies",
    name: [
      "MoviesDetailsCast",
      "MoviesMedia",
      "MoviesTopRated",
      "MoviesUpcoming",
      "MoviesNewest",
      "MoviesPopular",
      "MoviesDetails", "MoviesDetailsCast&Crew", "MoviesDetailsAwards"
    ],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "Popular",
        access_type: "none",
        page_link: "/movies/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "Newest",
        access_type: "none",
        page_link: "/movies/newest",
      },
      {
        label: "Upcoming",
        label_ko: "다가오는",
        key_name: "Upcoming",
        access_type: "none",
        page_link: "/movies/upcoming",
      },
      {
        label: "Top Rated",
        label_ko: "최고 등급",
        key_name: "TopRated",
        access_type: "none",
        page_link: "/movies/toprated",
      },
    ],
  },
  {
    label: "TV Shows",
    label_ko: "TV 프로그램",
    key_name: "TVShows",
    name: [
      "TvShowsPopular",
      "TvShowsDetails",
      "TvShowsDetailsEpisodes",
      "TvShowMedia",
      "TvShowsDetailsCast&Crew",
      "TvShowsNewest",
      "TvShowsUpcoming",
      "TvShowsTopRated",
      "TvShowsDetailsAwards", "TvShowsDetailsAwards"
    ],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularTV",
        access_type: "none",
        page_link: "/tvshows/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "NewestTV",
        access_type: "none",
        page_link: "/tvshows/newest",
      },
      {
        label: "Upcoming",
        label_ko: "다가오는",
        key_name: "UpcomingTV",
        access_type: "none",
        page_link: "/tvshows/upcoming",
      },
      {
        label: "Top Rated",
        label_ko: "최고 등급",
        key_name: "TopRated",
        access_type: "none",
        page_link: "/tvshows/toprated",
      },
    ],
  },
  {
    label: "Webtoons",
    label_ko: "웹툰",
    key_name: "Webtoons",
    name: ["WebtoonsPopular",
      "WebtoonsDetail", "WebtoonNewest",
      "WebtoonGoing", "CompletedWebtoon",
      "WebtoonMedia", "WebtoonDetailsEpisode", "WebtoonDetailsChar&Crew", "WebtoonDetailsAwards"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularWebtoon",
        access_type: "none",
        page_link: "/webtoons/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "Newest",
        access_type: "none",
        page_link: "/webtoons/newest",
      },
      {
        label: "On Going",
        label_ko: "다가오는",
        key_name: "Ongoing",
        access_type: "none",
        page_link: "/webtoons/going",
      },
      {
        label: "Completed",
        label_ko: "최고 등급",
        key_name: "Completed",
        access_type: "none",
        page_link: "/webtoons/complete",
      },
    ],
  },
  {
    label: "Videos",
    label_ko: "비디오",
    key_name: "Videos",
    name: ["VideoPopular", "VideoNewest", "VideoTrailer"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularVideo",
        access_type: "none",
        page_link: "/video/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "NewestVideo",
        access_type: "none",
        page_link: "/video/newest",
      },
      {
        label: "Trailer",
        label_ko: "트레일러",
        key_name: "TrailerVideo",
        access_type: "none",
        page_link: "/video/trailer",
      },
    ],
  },
  {
    label: "People",
    label_ko: "사람들",
    key_name: "People",
    name: ["PeoplePopular", "PeopleDetails", "PeopleMedia", "PeopleDetailAward"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularPeople",
        access_type: "none",
        page_link: "/people/popular",
      },
    ],
  },
  {
    label: "Awards",
    label_ko: "수상",
    key_name: "Awards",
    name: ["AwardsPopular", "AwardsDetail"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "All Events",
        label_ko: "모든 이벤트",
        key_name: "AllEvents",
        access_type: "none",
        page_link: "/awards/popular",
      },
    ],
  },
];

const headerMenuData = [
  {
    label: "Movies",
    label_ko: "영화 산업",
    key_name: "Movies",
    name: [
      "MoviesDetailsCast",
      "MoviesMedia",
      "MoviesTopRated",
      "MoviesUpcoming",
      "MoviesNewest",
      "MoviesPopular",
      "MoviesDetails", "MoviesDetailsCast&Crew", "MoviesDetailsAwards"
    ],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "Popular",
        access_type: "none",
        page_link: "/movies/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "Newest",
        access_type: "none",
        page_link: "/movies/newest",
      },
      {
        label: "Upcoming",
        label_ko: "다가오는",
        key_name: "Upcoming",
        access_type: "none",
        page_link: "/movies/upcoming",
      },
      {
        label: "Top Rated",
        label_ko: "최고 등급",
        key_name: "TopRated",
        access_type: "none",
        page_link: "/movies/toprated",
      },
    ],
  },
  {
    label: "TV Shows",
    label_ko: "TV 프로그램",
    key_name: "TVShows",
    name: [
      "TvShowsPopular",
      "TvShowsDetails",
      "TvShowsDetailsEpisodes",
      "TvShowMedia",
      "TvShowsDetailsCast&Crew",
      "TvShowsNewest",
      "TvShowsUpcoming",
      "TvShowsTopRated",
      "TvShowsDetailsAwards", "TvShowsDetailsAwards"
    ],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularTV",
        access_type: "none",
        page_link: "/tvshows/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "NewestTV",
        access_type: "none",
        page_link: "/tvshows/newest",
      },
      {
        label: "Upcoming",
        label_ko: "다가오는",
        key_name: "UpcomingTV",
        access_type: "none",
        page_link: "/tvshows/upcoming",
      },
      {
        label: "Top Rated",
        label_ko: "최고 등급",
        key_name: "TopRated",
        access_type: "none",
        page_link: "/tvshows/toprated",
      },
    ],
  },
  {
    label: "Webtoons",
    label_ko: "웹툰",
    key_name: "Webtoons",
    name: ["WebtoonsPopular",
      "WebtoonsDetail", "WebtoonNewest",
      "WebtoonGoing", "CompletedWebtoon",
      "WebtoonMedia", "WebtoonDetailsEpisode", "WebtoonDetailsChar&Crew", "WebtoonDetailsAwards"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularWebtoon",
        access_type: "none",
        page_link: "/webtoons/popular",
      },
      {
        label: "Newest",
        label_ko: "최신",
        key_name: "Newest",
        access_type: "none",
        page_link: "/webtoons/newest",
      },
      {
        label: "On Going",
        label_ko: "다가오는",
        key_name: "Ongoing",
        access_type: "none",
        page_link: "/webtoons/going",
      },
      {
        label: "Completed",
        label_ko: "최고 등급",
        key_name: "Completed",
        access_type: "none",
        page_link: "/webtoons/complete",
      },
    ],
  },
  // {
  //   label: "Videos",
  //   label_ko: "비디오",
  //   key_name: "Videos",
  //   name: ["VideoPopular", "VideoNewest", "VideoTrailer"],
  //   access_type: "read",
  //   status: false,
  //   subMenu: [
  //     {
  //       label: "Popular",
  //       label_ko: "인기 있는",
  //       key_name: "PopularVideo",
  //       access_type: "none",
  //       page_link: "/video/popular",
  //     },
  //     {
  //       label: "Newest",
  //       label_ko: "최신",
  //       key_name: "NewestVideo",
  //       access_type: "none",
  //       page_link: "/video/newest",
  //     },
  //     {
  //       label: "Trailer",
  //       label_ko: "트레일러",
  //       key_name: "TrailerVideo",
  //       access_type: "none",
  //       page_link: "/video/trailer",
  //     },
  //   ],
  // },
  {
    label: "People",
    label_ko: "사람들",
    key_name: "People",
    name: ["PeoplePopular", "PeopleDetails", "PeopleMedia", "PeopleDetailAward"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "Popular",
        label_ko: "인기 있는",
        key_name: "PopularPeople",
        access_type: "none",
        page_link: "/people/popular",
      },
    ],
  },
  {
    label: "Awards",
    label_ko: "수상",
    key_name: "Awards",
    name: ["AwardsPopular", "AwardsDetail"],
    access_type: "read",
    status: false,
    subMenu: [
      {
        label: "All Events",
        label_ko: "모든 이벤트",
        key_name: "AllEvents",
        access_type: "none",
        page_link: "/awards/popular",
      },
    ],
  },
];

export { headerMenuData, AdminheaderMenuData };
